// Dữ liệu minh họa. Giá là số nguyên VND; stock là số đơn vị đóng gói.
export const seedProducts = [
  {
    id: 1,
    name: "Cà chua tươi",
    category: "rau",
    price: 28000,
    unit: "500g",
    stock: 60,
    image: "/images/tomato.jpg",
    origin: "Đà Lạt",
    tag: "Được yêu thích",
    description:
      "Cà chua đỏ mọng, phù hợp cho món salad, canh và nước sốt. Bảo quản nơi thoáng mát hoặc trong ngăn mát tủ lạnh.",
  },
  {
    id: 2,
    name: "Bông cải xanh",
    category: "rau",
    price: 35000,
    unit: "500g",
    stock: 40,
    image: "/images/broccoli.jpg",
    origin: "Đà Lạt",
    tag: "Rau xanh",
    description:
      "Bông cải xanh giòn, dễ chế biến thành món hấp, xào hoặc súp. Rửa sạch và để ráo trước khi chế biến.",
  },
  {
    id: 3,
    name: "Cà rốt",
    category: "cu",
    price: 22000,
    unit: "500g",
    stock: 80,
    image: "/images/carrot.jpg",
    origin: "Đà Lạt",
    tag: "",
    description:
      "Cà rốt màu cam tự nhiên, dùng cho món hầm, salad hoặc nước ép. Giữ trong ngăn mát để duy trì độ giòn.",
  },
  {
    id: 4,
    name: "Táo đỏ",
    category: "qua",
    price: 65000,
    unit: "1kg",
    stock: 45,
    image: "/images/apple.jpg",
    origin: "Nhập khẩu",
    tag: "Trái cây",
    description:
      "Táo đỏ giòn, thích hợp để ăn trực tiếp hoặc làm bánh. Rửa sạch trước khi dùng; bảo quản trong ngăn mát.",
  },
  {
    id: 5,
    name: "Cam vàng",
    category: "qua",
    price: 42000,
    unit: "1kg",
    stock: 55,
    image: "/images/orange.jpg",
    origin: "Nhập khẩu",
    tag: "",
    description:
      "Cam vàng dùng để ăn trực tiếp hoặc vắt nước. Cất ở nơi khô thoáng, tránh ánh nắng trực tiếp.",
  },
  {
    id: 6,
    name: "Chuối vàng",
    category: "qua",
    price: 25000,
    unit: "1kg",
    stock: 50,
    image: "/images/banana.jpg",
    origin: "Đồng Nai",
    tag: "",
    description:
      "Chuối vàng mềm, phù hợp cho bữa sáng hoặc món sinh tố. Để ở nhiệt độ phòng, tránh nơi quá nóng.",
  },
  {
    id: 7,
    name: "Dưa leo",
    category: "rau",
    price: 18000,
    unit: "500g",
    stock: 70,
    image: "/images/cucumber.jpg",
    origin: "Lâm Đồng",
    tag: "",
    description:
      "Dưa leo giòn mát, dùng làm salad hoặc ăn kèm các món chính. Bảo quản trong ngăn mát và rửa sạch trước khi ăn.",
  },
  {
    id: 8,
    name: "Khoai tây",
    category: "cu",
    price: 30000,
    unit: "1kg",
    stock: 90,
    image: "/images/potato.jpg",
    origin: "Đà Lạt",
    tag: "",
    description:
      "Khoai tây dùng cho món hầm, súp hoặc nướng. Để ở nơi khô, tối và thoáng; không sử dụng củ đã xanh hoặc mọc mầm.",
  },
];
